spring:
  application:
  name: board-api

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:board;MODE=MYSQL


  jpa:
    hibernate:
      ddl-auto: create # 서버가 실행될때마다 db의 테이블 초기화 및 생성
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # 페이징 처리에 필요
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false # OSIV 비활성화

logging:
  level:
    org.hibernate.SQL: debug